### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by cangming99** [Dio93/LC-DuckMod#10]
I’ve encountered 2 bugs:

1、When I press the ‘E’ key while facing a duck, the console generates an error log related to the mod ‘pushcompany.’
2、I can now see the duck models in the dungeon, but when the ducks leave the dungeon, I’m unable to see the items they are carrying unless they drop them.

I really enjoy this mod and hope it continues to be updated and optimized.

**Comment by Dio93** [comment]
I fixed the bugs. The new version 1.5.0 is now on thunderstore.
