### ISSUE TITLE
[Feature Request] Pick up an item the duck is currently carrying

### ISSUE THREAD

**Issue by AtomicJuno** [Dio93/LC-DuckMod#2]
Love the duck mod. One of my all time favorites. This buddy goes into the main entrance while I go for the fire exit and it's great. But sometimes when I meet back up with the duck, it's holding a key. I can't grab it from it, and sometimes I really need it. It'd be neat if we could pick up the item the duck is carrying, or press [E] on it so that it drops the held item.

**Comment by Dio93** [comment]
Thank you very much :)
I haven't found a way yet to implement an [E] interaction. But you can hit the duck with a shovel and the duck will drop the item. You'll have 10 seconds to grab the item before the duck will grab it again.

**Comment by AtomicJuno** [comment]
That's useful information, good to know!

**Comment by Dio93** [comment]
In the new version 1.1.0 is interaction with [E] now possible.
The new version is available on thunderstore.
