### ISSUE TITLE
[Feature Request] Simple configuration options

### ISSUE THREAD

**Issue by AtomicJuno** [Dio93/LC-DuckMod#3]
A few ideas that might be good for the duck (Pardon me if not all of these are possible at the moment)

Carry amount : how many items the duck can carry
Duck speed : how fast the duck goes
Duck health : currently, it's invincible, but would be neat if it could die from hazards or enemies
Price of ducks: Ducks are free atm, but a config to alter the price could help balance it
Number of ducks: Only one duck can spawn at a time, but buying multiple could be fun

**Comment by Dio93** [comment]
I don't know how to create in-game menus, but I could add a text file where you can edit the configuration.

Carry amount, duck speed and price shouldn't be a problem.
Originally I wanted the duck to be killed by enemies, but I would have to play around with the enemy AI a lot. Maybe I could make a new mod including enemies that target the duck.

I have encountered sync issues when there is more than one duck. I haven't figured out how to fix this yet, but once I do I'll remove the restriction.

**Comment by NeatWolf** [comment]
Please leave the duck invulnerability as an option - I appreciate the idea of the duck being vulnerable (I'm using other mods to make enemies vulnerable to hazards as well) but... I already see myself debating with the rest of the crew about it. (personally I'd hate to see it die :( )

If more than a duck is going to be supported - I hope texture/skin variants are going to happen :P 

> I don't know how to create in-game menus

Have you considered leveraging @https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/? Normal cfg files are great as well.

**Comment by Dio93** [comment]
Alright, I will make it an option. 

Maybe there will be different textures :p

Thanks for the link. For now I will just use a normal cfg file. The next update is already in the making and will be on thunderstore in the next few days :)
