### ISSUE TITLE
duck stuck and won't follow from dropship

### ISSUE THREAD

**Issue by hoffor** [Dio93/LC-DuckMod#5]
at the company, unsure if happens elsewhere: duck spawns on top of one of the open doors on the dropship. once the dropship leaves, duck remains hovering in place and will not follow

**Comment by Dio93** [comment]
This is because there is no navmesh on the company moon. The duck needs navmesh to move.
I'll try to generate a navmesh when the duck spawns there.

**Comment by Dio93** [comment]
You can use [NavMeshInCompany](https://thunderstore.io/c/lethal-company/p/Kittenji/NavMeshInCompany/).
It should fix the issue.

**Comment by hoffor** [comment]
ah interesting. probably worth noting in the known issues on the readme. or add that mod as a dependency.. though i can imagine why you might not want to, especially since that causes masks to behave normally

**Comment by Dio93** [comment]
I just added it to the readme.

The new version is out. Check it on thunderstore :)
