### ISSUE TITLE
can't see the duck model

### ISSUE THREAD

**Issue by cangming99** [Dio93/LC-DuckMod#8]
When I entered the dungeon, I couldn't see the duck model, so what mod might have caused the conflict

**Comment by Dio93** [comment]
Which mods do you use? I know there are some issues with mods that add custom interiors.

**Comment by cangming99** [comment]
> Which mods do you use? I know there are some issues with mods that add custom interiors.
I think I know which mod is causing the conflict; it should be ‘CullFactory.’ Everything works fine after I disable CullFactory. Is there a way to make this mod compatible

**Comment by cangming99** [comment]
> Which mods do you use? I know there are some issues with mods that add custom interiors.

I think I know which mod is causing the conflict; it should be ‘CullFactory.’ Everything works fine after I disable CullFactory. Is there a way to make this mod compatible

**Comment by Dio93** [comment]
I found the issue. A fix will come with the next version.
