### ISSUE TITLE
[Feature Request] Ducks opening doors

### ISSUE THREAD

**Issue by AtomicJuno** [Dio93/LC-DuckMod#9]
Would it be possible for them to open the doors in the bunker?
The current strategy I use with the ducks is to enter the fire exit, while the duck goes into the bunker and pathfinds to me, grabbing items along the way.
It's extremely great for solo play but sometimes the ducks get stuck in doors since they cannot open. This would make a bit more sense for locked doors.

**Comment by Dio93** [comment]
I'm working on it but can't find the functions to open doors.
I also want the duck to use keys and open closed doors. 
As soon as I find a way to do this, I will implement it.
